Sonraki videoya geçme işlemi eklendi
anchovycation/pingu-front-end pull request #65
Opened 2022-08-24 21:28 UTC by saracalihan

![Pingu - Google Chrome 25 08 2022 00_25_56](https://user-images.githubusercontent.com/56413673/186526843-ef2ca602-0365-4665-9519-16b982c83724.png)

2022-08-25 10:18 UTC, beyzaerkan requested changes

2022-08-25 10:18 UTC, beyzaerkan commented on src/Components/YouTubePlayer/YouTubePlayer.jsx
> +  useEffect(() => {
aynı useEffect iki kere kullanılmış

2022-09-02 17:33 UTC, beyzaerkan requested changes

2022-09-02 17:33 UTC, beyzaerkan commented on src/Pages/WatchingRoom/WatchingRoom.jsx
> +      video: newVideo,
Burada böyle yapmanın nedeni nedir? Bence direk video, `video` olarak playlist, `playlist` olarak verilebilir.

2022-09-02 17:33 UTC, beyzaerkan commented on src/Pages/WatchingRoom/WatchingRoom.jsx
> +      setPlaylist(newPlaylist);
```suggestion
      setPlaylist(...newPlaylist);
```
Asıl sorun burada, dizileri kopyalamak için `spread` operatörü kullanmamız gerekiyor.

2022-09-02 17:38 UTC, beyzaerkan requested changes

2022-09-02 17:38 UTC, beyzaerkan commented on src/Pages/WatchingRoom/WatchingRoom.jsx
> +  const skipVideo = () => {
Bir hata da playlistte video olmadığı zaman ortaya çıkıyor. Kontrol edilebilir.

2022-09-02 17:57 UTC, saracalihan commented on src/Pages/WatchingRoom/WatchingRoom.jsx
> +      video: newVideo,
bu komponentte aynı isimlerde state de olduğu için kodda hangisi hangisiydi karıştırmamak adına böyle bir adlandırma tercih ettim.

2022-09-02 19:06 UTC, beyzaerkan approved these changes

2022-09-02 20:11 UTC, merged